version: "3"

services:
  phpapp:
    build:
      context: ./
      dockerfile: Dockerfile
    image: phpapp:123
    ports:
      - "81:80"
    volumes:
    - ./:/var/www/html
    container_name: php-app